name: .NET

on:
  push:
    branches: [ master, experimental ]
  pull_request:
    branches: [ master, experimental ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/th-schwarze/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./NetRevisionTask/bin/{Debug,Release}/*.nupkg --source https://nuget.pkg.github.com/th-schwarze --api-key ${GITHUB_TOKEN} --skip-duplicate --no-symbols true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
